const runwareModelConfig = {
  "aiModelConfigs": [
    {
      "id_name": "MainBase👌",
      "model": "runware:107@1",
      "credit_cost": 5,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["dataURI", "URL"],
      "outputFormat": "JPEG",
      "checkNSFW": false,
      "outputQuality": 95,
      "steps": 35,
      "scheduler": "Default",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "Logo🎨",
      "model": "runware:97@2",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 30,
      "scheduler": "Default",
      "seed": null,
      "CFGScale": 2,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "PixelArt🎮",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:689318@771472",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "AnimeStyle🌸",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:180891@838667",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "GhibliDream🌿",
      "model": "rundiffusion:120@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "outputQuality": 95,
      "steps": 35,
      "scheduler": "Default",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "khialmaster:1411365@1595505",
        "weight": 1
      }],
      "refiner": null
    },    
    {
      "id_name": "InkStyle🖋️",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:73305@890482",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "RetroAnime📺",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:721039@806265",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "CinematicShot🎬",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:432586@857668",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "WizardWitch🧙‍♂️✨",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:308147@880134",
        "weight": 0.85
      }],
      "refiner": null
    },
    {
      "id_name": "BossBattle⚔️",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:330173@812295",
        "weight": 0.85
      }],
      "refiner": null
    },
    {
      "id_name": "80sFantasy🎥",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "khialmaster:789313@1287297",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "Illustration🎨",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:437067@1000905",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "DarkFantasy🌑",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:660112@738658",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "Monsters2🦠",
      "model": "rundiffusion:120@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:878368@983288",
        "weight": 0.9
      }],
      "refiner": null
    },
    {
      "id_name": "Monsters👁️",
      "model": "rundiffusion:120@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "khialmaster:86377@759611",
        "weight": 0.9
      }],
      "refiner": null
    },
    {
      "id_name": "BodyHorror🩸",
      "model": "rundiffusion:120@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:126471@743280",
        "weight": 0.9
      }],
      "refiner": null
    },
    {
      "id_name": "3DRender🎭",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:742211@830009",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "CyberAnime☣",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "civitai:128568@747534",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "Gothic Niji🖤",
      "model": "rundiffusion:120@100",
      "credit_cost": 2.5,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "khialmaster:915918@1189748",
        "weight": 1
      }],
      "refiner": null
    },
    {
      "id_name": "Furry🐯",
      "model": "rundiffusion:120@100",
      "credit_cost": 2.5,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{
        "model": "khialmaster:310964@1525003",
        "weight": 0.8
      }],
      "refiner": null
    },     
    {
      "id_name": "Photography📷",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 896,
      "height": 1152,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 40,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [
        {
          "model": "civitai:652699@993999",
          "weight": 0.87
        }       
      ],
      "refiner": null
    },
    {
      "id_name": "Photography2📷",
      "model": "khialmaster:978314@1413133",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 832,
      "height": 1216,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 50,
      "scheduler": "DPM++ 2M Beta",
      "seed": null,
      "CFGScale": 3,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },  
    {
      "id_name": "Photography3📷",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 832,
      "height": 1216,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 40,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [
        {
          "model": "civitai:639937@810340",
          "weight": 0.8
        }       
      ],
      "refiner": null
    },
    {
      "id_name": "Photography4📷",
      "model": "khialmaster:978314@1413133",
      "credit_cost": 5,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 832,
      "height": 1216,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 60,
      "scheduler": "DPM++ 2M Beta",
      "seed": null,
      "CFGScale": 3,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [{"model":"khialmaster:1551668@1755780", "weight":0.9}],
      "refiner": null
    },    
    {
      "id_name": "RealFantasy🕷",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 40,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [
        {
          "model": "civitai:599757@1227179",
          "weight": 1
        }
      ],
      "refiner": null
    },
    {
      "id_name": "MythicFantasy🕷",
      "model": "rundiffusion:120@100",
      "credit_cost": 2,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 40,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [
        {
          "model": "civitai:599757@753053",
          "weight": 1
        }
      ],
      "refiner": null
    },
    {
      "id_name": "NSFW📛",
      "model": "civitai:372465@1763661",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "score_6, score_5, score_4, text, censored, deformed, bad hand",
      "width": 896,
      "height": 1152,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 50,
      "scheduler": "DPM++ 2M SDE Karras",
      "seed": null,
      "CFGScale": 6,
      "clipSkip": 0,
      "usePromptWeighting": 1,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "NSFW2📛",
      "model": "civitai:443821@1838857",
      "credit_cost": 3.5,
      "positivePrompt": "",
      "negativePrompt": "score_6, score_5, score_4, text, censored, deformed, bad hand",
      "width": 896,
      "height": 1152,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 50,
      "scheduler": "DPM++ 2M SDE Karras",
      "seed": null,
      "CFGScale": 5,
      "clipSkip": 0,
      "usePromptWeighting": 1,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "NSFW3📛",
      "model": "civitai:443821@1791065",
      "credit_cost": 5,
      "positivePrompt": "",
      "negativePrompt": "Stable_Yogis_PDXL_Negatives2, Stable_Yogis_PDXL_Negatives2-neg",
      "width": 896,
      "height": 1152,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 50,
      "scheduler": "DPM++ 2M SDE Karras",
      "seed": null,
      "CFGScale": 5,
      "clipSkip": 0,
      "usePromptWeighting": 1,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "embedding": ["khialmaster:1331980@1503873", "khialmaster:1331758@1503612"],
      "refiner": null
    },    
    {
      "id_name": "AnimeNSFW📛",
      "model": "civitai:257749@290640",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "easynegative, core_6, score_5, score_4, worst quality, low quality, text, censored, deformed, bad hand, blurry, (watermark), multiple phones, weights, bunny ears, extra hands,",
      "width": 896,
      "height": 1152,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 30,
      "scheduler": "Euler A",
      "seed": null,
      "CFGScale": 8.5,
      "clipSkip": 0,
      "usePromptWeighting": 1,
      "retry": 2,
      "controlNet": [],
      "embedding": ["civitai:7808@9208"],
      "lora": [{"model": "civitai:300005@436219", "weight": 0.65}, {"model": "civitai:888231@1029540", "weight": 0.55}],
      "refiner": null
    },
    {
      "id_name": "Detailed💯",
      "model": "rundiffusion:120@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 40,
      "scheduler": "Euler",
      "seed": null,
      "CFGScale": 4,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [
        {
          "model": "khialmaster:562866@984672",
          "weight": 0.7
        },
        {
          "model": "khialmaster:646411@1249246",
          "weight": 0.4
        }      
      ],
      "refiner": null
    },   
    {
      "id_name": "Basic✔",
      "model": "rundiffusion:120@100",
      "credit_cost": 1,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 33,
      "scheduler": "Euler Beta",
      "seed": null,
      "CFGScale": 3,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "💚Free💚",
      "model": "rundiffusion:110@101",
      "credit_cost": 0,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 512,
      "height": 512,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 4,
      "scheduler": "Euler Beta",
      "seed": null,
      "CFGScale": 1,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },    
    {
      "id_name": "Pro⚜Creative",
      "model": "rundiffusion:130@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler Beta",
      "seed": null,
      "CFGScale": 3.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "Pro📸Realism",
      "model": "rundiffusion:130@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler Beta",
      "seed": null,
      "CFGScale": 2.5,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "Pro🎨Mixed",
      "model": "rundiffusion:130@100",
      "credit_cost": 3,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 35,
      "scheduler": "Euler Beta",
      "seed": null,
      "CFGScale": 3,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "Pro+🪷",
      "model": "runware:97@1",
      "credit_cost": 3.5,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 30,
      "scheduler": "Default",
      "seed": null,
      "CFGScale": 2.8,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "Basic+🪷",
      "model": "runware:97@2",
      "credit_cost": 1.5,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 20,
      "scheduler": "Default",
      "seed": null,
      "CFGScale": 1,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    },
    {
      "id_name": "Fast+🪷",
      "model": "runware:97@2",
      "credit_cost": 1,
      "positivePrompt": "",
      "negativePrompt": "",
      "width": 1024,
      "height": 1024,
      "numberResults": 1,
      "outputType": ["URL"],
      "outputFormat": "PNG",
      "checkNSFW": false,
      "steps": 16,
      "scheduler": "Default",
      "seed": null,
      "CFGScale": 1,
      "clipSkip": 0,
      "usePromptWeighting": 0,
      "retry": 2,
      "controlNet": [],
      "lora": [],
      "refiner": null
    }              
  ]
}
// Export the config for ES modules
export default runwareModelConfig;

// Also export as named export for compatibility
export { runwareModelConfig };
